import trFlag from "../assets/flags/turkey.png"
import itFlag from "../assets/flags/italy.png"
import frFlag from "../assets/flags/france.png"
import esFlag from "../assets/flags/spain.png"
import enFlag from "../assets/flags/united-kingdom.png"

export const countryInfo = [
  { country: 'Afghanistan', code: 'AF', phone: '93' },
  { country: 'Albania', code: 'AL', phone: '355' },
  { country: 'Algeria', code: 'DZ', phone: '213' },
  { country: 'Andorra', code: 'AD', phone: '376' },
  { country: 'Angola', code: 'AO', phone: '244' },
  { country: 'Argentina', code: 'AR', phone: '54' },
  { country: 'Armenia', code: 'AM', phone: '374' },
  { country: 'Australia', code: 'AU', phone: '61' },
  { country: 'Austria', code: 'AT', phone: '43' },
  { country: 'Azerbaijan', code: 'AZ', phone: '994' },
  { country: 'Bahamas', code: 'BS', phone: '1-242' },
  { country: 'Bahrain', code: 'BH', phone: '973' },
  { country: 'Bangladesh', code: 'BD', phone: '880' },
  { country: 'Barbados', code: 'BB', phone: '1-246' },
  { country: 'Belarus', code: 'BY', phone: '375' },
  { country: 'Belgium', code: 'BE', phone: '32' },
  { country: 'Belize', code: 'BZ', phone: '501' },
  { country: 'Benin', code: 'BJ', phone: '229' },
  { country: 'Bhutan', code: 'BT', phone: '975' },
  { country: 'Bolivia', code: 'BO', phone: '591' },
  { country: 'Bosnia and Herzegovina', code: 'BA', phone: '387' },
  { country: 'Botswana', code: 'BW', phone: '267' },
  { country: 'Brazil', code: 'BR', phone: '55' },
  { country: 'Brunei', code: 'BN', phone: '673' },
  { country: 'Bulgaria', code: 'BG', phone: '359' },
  { country: 'Burkina Faso', code: 'BF', phone: '226' },
  { country: 'Burundi', code: 'BI', phone: '257' },
  { country: 'Cabo Verde', code: 'CV', phone: '238' },
  { country: 'Cambodia', code: 'KH', phone: '855' },
  { country: 'Cameroon', code: 'CM', phone: '237' },
  { country: 'Canada', code: 'CA', phone: '1' },
  { country: 'Central African Republic', code: 'CF', phone: '236' },
  { country: 'Chad', code: 'TD', phone: '235' },
  { country: 'Chile', code: 'CL', phone: '56' },
  { country: 'China', code: 'CN', phone: '86' },
  { country: 'Colombia', code: 'CO', phone: '57' },
  { country: 'Comoros', code: 'KM', phone: '269' },
  { country: 'Congo (Brazzaville)', code: 'CG', phone: '242' },
  { country: 'Congo (Kinshasa)', code: 'CD', phone: '243' },
  { country: 'Costa Rica', code: 'CR', phone: '506' },
  { country: 'Croatia', code: 'HR', phone: '385' },
  { country: 'Cuba', code: 'CU', phone: '53' },
  { country: 'Cyprus', code: 'CY', phone: '357' },
  { country: 'Czech Republic', code: 'CZ', phone: '420' },
  { country: 'Denmark', code: 'DK', phone: '45' },
  { country: 'Djibouti', code: 'DJ', phone: '253' },
  { country: 'Dominica', code: 'DM', phone: '1-767' },
  { country: 'Dominican Republic', code: 'DO', phone: '1-809' },
  { country: 'Ecuador', code: 'EC', phone: '593' },
  { country: 'Egypt', code: 'EG', phone: '20' },
  { country: 'El Salvador', code: 'SV', phone: '503' },
  { country: 'Equatorial Guinea', code: 'GQ', phone: '240' },
  { country: 'Eritrea', code: 'ER', phone: '291' },
  { country: 'Estonia', code: 'EE', phone: '372' },
  { country: 'Eswatini', code: 'SZ', phone: '268' },
  { country: 'Ethiopia', code: 'ET', phone: '251' },
  { country: 'Fiji', code: 'FJ', phone: '679' },
  { country: 'Finland', code: 'FI', phone: '358' },
  { country: 'France', code: 'FR', phone: '33' },
  { country: 'Gabon', code: 'GA', phone: '241' },
  { country: 'Gambia', code: 'GM', phone: '220' },
  { country: 'Georgia', code: 'GE', phone: '995' },
  { country: 'Germany', code: 'DE', phone: '49' },
  { country: 'Ghana', code: 'GH', phone: '233' },
  { country: 'Greece', code: 'GR', phone: '30' },
  { country: 'Grenada', code: 'GD', phone: '1-473' },
  { country: 'Guatemala', code: 'GT', phone: '502' },
  { country: 'Guinea', code: 'GN', phone: '224' },
  { country: 'Guinea-Bissau', code: 'GW', phone: '245' },
  { country: 'Guyana', code: 'GY', phone: '592' },
  { country: 'Haiti', code: 'HT', phone: '509' },
  { country: 'Honduras', code: 'HN', phone: '504' },
  { country: 'Hungary', code: 'HU', phone: '36' },
  { country: 'Iceland', code: 'IS', phone: '354' },
  { country: 'India', code: 'IN', phone: '91' },
  { country: 'Indonesia', code: 'ID', phone: '62' },
  { country: 'Iran', code: 'IR', phone: '98' },
  { country: 'Iraq', code: 'IQ', phone: '964' },
  { country: 'Ireland', code: 'IE', phone: '353' },
  { country: 'Israel', code: 'IL', phone: '972' },
  { country: 'Italy', code: 'IT', phone: '39' },
  { country: 'Jamaica', code: 'JM', phone: '1-876' },
  { country: 'Japan', code: 'JP', phone: '81' },
  { country: 'Jordan', code: 'JO', phone: '962' },
  { country: 'Kazakhstan', code: 'KZ', phone: '7' },
  { country: 'Kenya', code: 'KE', phone: '254' },
  { country: 'Kiribati', code: 'KI', phone: '686' },
  { country: 'Kuwait', code: 'KW', phone: '965' },
  { country: 'Kyrgyzstan', code: 'KG', phone: '996' },
  { country: 'Laos', code: 'LA', phone: '856' },
  { country: 'Latvia', code: 'LV', phone: '371' },
  { country: 'Lebanon', code: 'LB', phone: '961' },
  { country: 'Lesotho', code: 'LS', phone: '266' },
  { country: 'Liberia', code: 'LR', phone: '231' },
  { country: 'Libya', code: 'LY', phone: '218' },
  { country: 'Liechtenstein', code: 'LI', phone: '423' },
  { country: 'Lithuania', code: 'LT', phone: '370' },
  { country: 'Luxembourg', code: 'LU', phone: '352' },
  { country: 'Madagascar', code: 'MG', phone: '261' },
  { country: 'Malawi', code: 'MW', phone: '265' },
  { country: 'Malaysia', code: 'MY', phone: '60' },
  { country: 'Maldives', code: 'MV', phone: '960' },
  { country: 'Mali', code: 'ML', phone: '223' },
  { country: 'Malta', code: 'MT', phone: '356' },
  { country: 'Marshall Islands', code: 'MH', phone: '692' },
  { country: 'Mauritania', code: 'MR', phone: '222' },
  { country: 'Mauritius', code: 'MU', phone: '230' },
  { country: 'Mexico', code: 'MX', phone: '52' },
  { country: 'Micronesia', code: 'FM', phone: '691' },
  { country: 'Moldova', code: 'MD', phone: '373' },
  { country: 'Monaco', code: 'MC', phone: '377' },
  { country: 'Mongolia', code: 'MN', phone: '976' },
  { country: 'Montenegro', code: 'ME', phone: '382' },
  { country: 'Morocco', code: 'MA', phone: '212' },
  { country: 'Mozambique', code: 'MZ', phone: '258' },
  { country: 'Myanmar', code: 'MM', phone: '95' },
  { country: 'Namibia', code: 'NA', phone: '264' },
  { country: 'Nauru', code: 'NR', phone: '674' },
  { country: 'Nepal', code: 'NP', phone: '977' },
  { country: 'Netherlands', code: 'NL', phone: '31' },
  { country: 'New Zealand', code: 'NZ', phone: '64' },
  { country: 'Nicaragua', code: 'NI', phone: '505' },
  { country: 'Niger', code: 'NE', phone: '227' },
  { country: 'Nigeria', code: 'NG', phone: '234' },
  { country: 'North Macedonia', code: 'MK', phone: '389' },
  { country: 'Norway', code: 'NO', phone: '47' },
  { country: 'Oman', code: 'OM', phone: '968' },
  { country: 'Pakistan', code: 'PK', phone: '92' },
  { country: 'Palau', code: 'PW', phone: '680' },
  { country: 'Panama', code: 'PA', phone: '507' },
  { country: 'Papua New Guinea', code: 'PG', phone: '675' },
  { country: 'Paraguay', code: 'PY', phone: '595' },
  { country: 'Peru', code: 'PE', phone: '51' },
  { country: 'Philippines', code: 'PH', phone: '63' },
  { country: 'Poland', code: 'PL', phone: '48' },
  { country: 'Portugal', code: 'PT', phone: '351' },
  { country: 'Qatar', code: 'QA', phone: '974' },
  { country: 'Romania', code: 'RO', phone: '40' },
  { country: 'Russia', code: 'RU', phone: '7' },
  { country: 'Rwanda', code: 'RW', phone: '250' },
  { country: 'Saint Kitts and Nevis', code: 'KN', phone: '1-869' },
  { country: 'Saint Lucia', code: 'LC', phone: '1-758' },
  { country: 'Saint Vincent and the Grenadines', code: 'VC', phone: '1-784' },
  { country: 'Samoa', code: 'WS', phone: '685' },
  { country: 'San Marino', code: 'SM', phone: '378' },
  { country: 'Sao Tome and Principe', code: 'ST', phone: '239' },
  { country: 'Saudi Arabia', code: 'SA', phone: '966' },
  { country: 'Senegal', code: 'SN', phone: '221' },
  { country: 'Serbia', code: 'RS', phone: '381' },
  { country: 'Seychelles', code: 'SC', phone: '248' },
  { country: 'Sierra Leone', code: 'SL', phone: '232' },
  { country: 'Singapore', code: 'SG', phone: '65' },
  { country: 'Slovakia', code: 'SK', phone: '421' },
  { country: 'Slovenia', code: 'SI', phone: '386' },
  { country: 'Solomon Islands', code: 'SB', phone: '677' },
  { country: 'Somalia', code: 'SO', phone: '252' },
  { country: 'South Africa', code: 'ZA', phone: '27' },
  { country: 'South Korea', code: 'KR', phone: '82' },
  { country: 'South Sudan', code: 'SS', phone: '211' },
  { country: 'Spain', code: 'ES', phone: '34' },
  { country: 'Sri Lanka', code: 'LK', phone: '94' },
  { country: 'Sudan', code: 'SD', phone: '249' },
  { country: 'Suriname', code: 'SR', phone: '597' },
  { country: 'Sweden', code: 'SE', phone: '46' },
  { country: 'Switzerland', code: 'CH', phone: '41' },
  { country: 'Syria', code: 'SY', phone: '963' },
  { country: 'Taiwan', code: 'TW', phone: '886' },
  { country: 'Tajikistan', code: 'TJ', phone: '992' },
  { country: 'Tanzania', code: 'TZ', phone: '255' },
  { country: 'Thailand', code: 'TH', phone: '66' },
  { country: 'Timor-Leste', code: 'TL', phone: '670' },
  { country: 'Togo', code: 'TG', phone: '228' },
  { country: 'Tonga', code: 'TO', phone: '676' },
  { country: 'Trinidad and Tobago', code: 'TT', phone: '1-868' },
  { country: 'Tunisia', code: 'TN', phone: '216' },
  { country: 'Turkey', code: 'TR', phone: '90' },
  { country: 'Turkmenistan', code: 'TM', phone: '993' },
  { country: 'Tuvalu', code: 'TV', phone: '688' },
  { country: 'Uganda', code: 'UG', phone: '256' },
  { country: 'Ukraine', code: 'UA', phone: '380' },
  { country: 'United Arab Emirates', code: 'AE', phone: '971' },
  { country: 'United Kingdom', code: 'GB', phone: '44' },
  { country: 'United States', code: 'US', phone: '1' },
  { country: 'Uruguay', code: 'UY', phone: '598' },
  { country: 'Uzbekistan', code: 'UZ', phone: '998' },
  { country: 'Vanuatu', code: 'VU', phone: '678' },
  { country: 'Vatican City', code: 'VA', phone: '379' },
  { country: 'Venezuela', code: 'VE', phone: '58' },
  { country: 'Vietnam', code: 'VN', phone: '84' },
  { country: 'Yemen', code: 'YE', phone: '967' },
  { country: 'Zambia', code: 'ZM', phone: '260' },
  { country: 'Zimbabwe', code: 'ZW', phone: '263' }
]

export const jobType = [

  { name: "businessowner" },
  { name: "chef" },
  { name: "f&b" },
  { name: "architect" },
  { name: "other" },
]

export const languages = [
  {
    title: "tr",
    icon: trFlag
  },
  {
    title: "en",
    icon: enFlag
  },
  {
    title: "it",
    icon: itFlag
  },

  {
    title: "es",
    icon: esFlag
  },

  {
    title: "fr",
    icon: frFlag
  },



]